# Koszt zalozenia teamu
koszt-stworzenia: 50000.0

# Wszystkie wiadomosci w pluginie. Mozesz uzywac kodow kolorow &.
messages:
  juz-w-teamie: "&9Team &8» &7Jestes juz w teamie."
  tag-zajety: "&9Team &8» &7Team o takim tagu juz istnieje."
  brak-pieniedzy: "&9Team &8» &7Nie masz wystarczajaco pieniedzy (&e%cost%&7)."
  blad-pobierania-pieniedzy: "&9Team &8» &7Wystapil blad podczas pobierania pieniedzy."
  team-stworzony: "&9Team &8» &7Stworzyles team o tagu: &e%tag%"
  nie-jestes-liderem: "&9Team &8» &7Nie jestes liderem teamu."
  gracz-offline: "&9Team &8» &7Gracz jest offline."
  gracz-juz-w-teamie: "&9Team &8» &7Ten gracz jest juz w innym teamie."
  zaproszono-gracza: "&9Team &8» &7Zaproszono gracza &e%player%&7 do teamu."
  otrzymano-zaproszenie: "&9Team &8» &7Otrzymales zaproszenie do teamu &e%tag%&7. Wpisz &e/team akceptuj&7."
  brak-zaproszen: "&9Team &8» &7Nie masz zadnych zaproszen."
  team-nie-istnieje: "&9Team &8» &7Team, do ktorego zostales zaproszony, juz nie istnieje."
  dolaczono-do-teamu: "&9Team &8» &7Dolaczyles do teamu &e%tag%&7."
  gracz-dolaczyl: "&9Team &8» &7Gracz &e%player% &7dolaczyl do teamu."
  gracz-nie-w-teamie: "&9Team &8» &7Tego gracza nie ma w Twoim teamie."
  nie-mozna-wyrzucic-zalozyciela: "&9Team &8» &7Nie mozesz wyrzucic zalozyciela."
  gracz-wyrzucony: "&9Team &8» &7Gracz &e%player%&7 zostal wyrzucony."
  tylko-zalozyciel-usuniecie: "&9Team &8» &7Tylko zalozyciel moze usunac team."
  team-rozwiazany: "&9Team &8» &7Team zostal rozwiazany."
  tylko-zalozyciel-lider: "&9Team &8» &7Tylko zalozyciel moze nadawac lidera."
  gracz-juz-liderem: "&9Team &8» &7Ten gracz jest juz liderem."
  awans-na-lidera: "&9Team &8» &7Gracz &e%player%&7 zostal nowym liderem."
  tylko-zalozyciel-degrad: "&9Team &8» &7Tylko zalozyciel moze degradowac."
  gracz-nie-jest-liderem: "&9Team &8» &7Ten gracz nie jest liderem."
  degrad-lidera: "&9Team &8» &7Gracz &e%player%&7 nie jest juz liderem."
  pvp-zmienione: "&9Team &8» &7PVP w teamie zostalo %status%&7."
  status-pvp-wlaczone: "&awlaczone"
  status-pvp-wylaczone: "&cwylaczone"
  brak-teamu: "&9Team &8» &7Nie jestes w zadnym teamie."
  zalozyciel-nie-moze-opuscic: "&9Team &8» &7Nie mozesz opuscic teamu, jestes zalozycielem. Uzyj /team usun."
  gracz-opuscil-team: "&9Team &8» &7Gracz &e%player% &7opuscil team."
  opusciles-team: "&9Team &8» &7Opusciles team."
  poprawne-uzycie: "&9Team &8» &7Poprawne uzycie: &e%usage%"
